### ISSUE TITLE
trying to adapt to REST API (laravel) to get mail messages for all users

### ISSUE THREAD

**Issue by heberfomin** [microsoftgraph/msgraph-sample-phpapp#11]
Hi there,
I'm trying to adapt the blade version you made to a rest one. 
The purpose of the application is to get sent/received mail messages to put in a CRM database account. 
in our endPoint method the user (Sales Rep) will provide his user/password, so then I used the post like this:
https://login.microsoftonline.com/{myTenantID}/oauth2/token 
with the parameters:
    grant_type=password,
    client_id=myAppId,
    client_secret=mySecret,
    username=salesrep@myorganization.com,
    password=salesreppwd,
    resource=https://graph.microsoft.com/,
    scope=user.read,calendars.read,MailboxSettings.Read,Mail.read,Mail.Send
it works,I received access token and also refresh token, but I can only receive User.Read scope.
How can I change that to receive also calendars read/write and emails read/write scopes?

Thanks in advance

**Comment by jasonjoh** [comment]
The URL you're POSTing to is the Azure v1 OAuth endpoint. This endpoint doesn't use the `scope` parameter, so you have to configure the specific permissions you want on the app registration. The default Graph scope is User.Read when you register an app, so that's why you're getting that back. Add the scopes you want and it should work for you.

It's best to post these types of OAuth questions to Stack Overflow, since a lot of the Azure folks watch the Azure-related tags there.
