### ISSUE TITLE
Composer  microsoft/microsoft-graph version bug

### ISSUE THREAD

**Issue by laradude** [microsoftgraph/msgraph-sample-phpapp#66]
### Where did you get the code?

- [x] Downloaded from GitHub
- [x] Downloaded from the [Microsoft Graph quick start tool](https://developer.microsoft.com/graph/quick-start)
- [ ] Followed the tutorial from [Microsoft Graph tutorials](https://docs.microsoft.com/graph/tutorials)

### Describe the bug

Composer cannot install the project, because of the invalid microsoft-graph version. This is located in the composer.json file https://github.com/microsoftgraph/msgraph-training-phpapp/blob/68bfcb823cf5b8c74e3c9ed47c630ccbf35bbbe4/demo/graph-tutorial/composer.json#L18

### To Reproduce

Following the quick start guide for PHP: https://developer.microsoft.com/en-us/graph/quick-start

1. Unzip the downloaded package to a directory, and go to the graph-tutorial directory in your command-line tool.
1. Type composer install to install the project dependencies.

### Expected behavior

The composer install process should complete package installation without error. 

### Dependency versions
microsoft/microsoft-graph: "^1.49"
https://github.com/microsoftgraph/msgraph-sdk-php

### Additional context
The bug was corrected using a valid version number, `"^1.49"`

**Comment by SomeDevWeb** [comment]
Hi. I have this issue too.

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires microsoft/microsoft-graph dev-zengin/php-version, found microsoft/microsoft-graph[dev-fix/update-docs/1635333565, ..., dev-beta/pipelinebuild/64036, 0.1.0, 0.1.1, 1.0.0, ..., 1.50.0, 2.0.0-RC1, 2.0.0-RC2, 2.0.0-RC3] but it does not match the constraint.

Do I need to have Laravel installed to use MS graph?

**Comment by laradude** [comment]
@SomeDevWeb 

Change the below line in your composer.json file to `microsoft/microsoft-graph: "^1.49"`. 

https://github.com/microsoftgraph/msgraph-training-phpapp/blob/68bfcb823cf5b8c74e3c9ed47c630ccbf35bbbe4/demo/graph-tutorial/composer.json#L18

**Comment by jasonjoh** [comment]
@SomeDevWeb you do NOT need Laravel, this sample just uses Laravel framework to structure the web app.

**Comment by SomeDevWeb** [comment]
**Thanks, both!** That line fix worked and the rest of the setup went ok. 
One more issue though, after I did 'php artisan serv' I got the right message, but the actual web page didn't load at all.                                                                                                                                                                                                     Starting Laravel development server: http://127.0.0.1:8000 
So I researched a bit and someone suggested this command which worked for me. Maybe you can put it in your Quickstart steps:
`php -S 127.0.0.1:8000 -t public`

**Comment by SomeDevWeb** [comment]
Thanks again. You are very kind!
Another very important aspect please, related to the "Laravel" question.
The only reason I need to use MS API is because of a job request for creating a calendar meeting in MS outlook from a third party PHP system.
I never used Ms api and I don't ever want to get involved with it, but since I have to do this, can you please suggest the most bare-bone PHP library that can be used and some little code examples for creating that meeting or event, so the pain can be smaller...
This actually could be an example to go in the official documentation as well.
Thank you so much for all your help and time!!!

**Comment by noahheck** [comment]
@SomeDevWeb This training app just uses Laravel to help people get started using the Microsoft Graph API SDK library, but there is no requirement to use Laravel in order to use the Graph API. The Graph API library is a separate project: https://github.com/microsoftgraph/msgraph-sdk-php. The documentation for that project includes [code samples](https://github.com/microsoftgraph/msgraph-sdk-php/tree/dev/docs) that show basic usage of the SDK. You can download the files directly from there, or you can use [Composer](https://getcomposer.org) to install the sdk library into your own Composer managed project:

`composer require microsoft/microsoft-graph`

**Comment by SSzretter** [comment]
In case it helps someone else, I changed my composer to this and it worked:   "microsoft/microsoft-graph": "^1.51"
